### ISSUE TITLE
ABOVE_MAX_BET_AMOUNT error with "FILLANDKILL" bets

### ISSUE THREAD

**Issue by arccosmos** [pinnacleapi/pinnacleapi-documentation#36]
Since the middle of December I periodically get this type of error.
I didn't change anything in my code, it was worked perfectly.

Now I get something like this:

{'TIMESTAMP': '2021-01-26 19:58:09.175653', 'status': 'PROCESSED_WITH_ERROR', 'errorCode': 'ABOVE_MAX_BET_AMOUNT', 'uniqueRequestId': '6413d4d3-8540-42c4-82c2-c32e60740e20', 'straightBet': None, 'Latency': 0.218156}

 The definition for FILLANDKILL fill_type: _If the stake is over the max limit, bet will be placed on max limit, otherwise it will be placed on specified stake_. So this error looks very strange.

Sometimes second try can help, sometimes it can't be betted anyway.

**Comment by pinnacleapi** [comment]
Yes, we had an issue, it should be resolved now.

**Comment by arccosmos** [comment]
Looks like it's still not resolved.
![](https://i.gyazo.com/0ce40dd2730c9d97a1eaed49db1bca86.png)

**Comment by pinnacleapi** [comment]
Another fix was deployed on March 15th, should be good now.
